appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: xoiIhVHqzwJ18Jgzkwn6blNgjZ9XmUXv3zDl184S7C9xgmqQlTZ3lj8Gh2nXzUvC5FtT+v4kpteb2nRPo8nyzdXzucjpM390D0FvDHY0/hbzPGezFz6AEEDJ/FGfG3RXWFHRbY9ikbRKYuKf5UOL/M4Xi9yHebeGgLKXU6QKdSuYlYKu/nFf12CPSHxulswkKDw0azAOh0LgECDq9KMrmEsMz3o5Q3/i7XKrnAtpDGP9Gl7KsNFbT6M73g3KvaYL4WGZKyNUbQhPb3CtT0rJfTcNz7q2Im+9vBHk9XC2BulCBu8B3eW1SlqZwiBEybNWzwK38Sf309VDBBrIRurkgjnOfO5ba4hUsWCrV4yP6NoYwyppkWsxovr10qwoZmhOx+VW7i2GvsvDJghML+VNcxhROeHdXeDXRr8m8nJCpK05emum9Da4WrfFUFohTf7XtuFJrlob1xE4BzGnn6nqQd2uH9ZOIEblioFs4lRHECXhptZb/eRePFNLuCPfc80WRt9hrcO4UMqVEvdRFJl8g8Mpzmx4luV2wtuQASo0ytOEyyT146ciOdfFFXzRdSJejByzfl+EHUKHHQE2WOeP5RWnYqA0WZs1xp5Ry5KH/bpTAW1PBz2C8l306oIhpAZJOtp4ZF5uFJiw26sdXE+4/HksuwU72SSgCo/GTM4KCy0=}
